name: Build aria2c.exe

on:

  workflow_dispatch:

env:
  HOST: x86_64-w64-mingw32

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      
      - name: Update apt-get
        run: |
            sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends \
                make binutils autoconf automake autotools-dev libtool \
                patch ca-certificates \
                pkg-config git curl dpkg-dev gcc-mingw-w64 g++-mingw-w64 \
                autopoint libcppunit-dev libxml2-dev libgcrypt20-dev lzip
                
      - name: Download
        run: |
            curl -L -O https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz && \
            curl -L -O https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.bz2 && \
            curl -L -O https://www.sqlite.org/2021/sqlite-autoconf-3360000.tar.gz && \
            curl -L -O http://zlib.net/zlib-1.2.11.tar.gz && \
            curl -L -O https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz && \
            curl -L -O https://www.libssh2.org/download/libssh2-1.9.0.tar.gz && \
            curl -L -O https://github.com/libssh2/libssh2/commit/ba149e804ef653cc05ed9803dfc94519ce9328f7.patch
            
      - name: Install gmp
        run: |
            tar xf gmp-6.2.1.tar.lz && \
            cd gmp-6.2.1 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --disable-cxx \
                --enable-fat \
                CFLAGS="-mtune=generic -O2 -g0" && \
            sudo make install

      - name: Install expat
        run: |
            tar xf expat-2.4.1.tar.bz2 && \
            cd expat-2.4.1 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
            sudo make install
            
      - name: Install sqlite-autoconf
        run: |
            tar xf sqlite-autoconf-3360000.tar.gz && \
            cd sqlite-autoconf-3360000 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
            sudo make install

      - name: Install zlib
        run: |
            tar xf zlib-1.2.11.tar.gz && \
            cd zlib-1.2.11 && \
            CC=${{ env.HOST }}-gcc \
            AR=${{ env.HOST }}-ar \
            LD=${{ env.HOST }}-ld \
            RANLIB=${{ env.HOST }}-ranlib \
            STRIP=${{ env.HOST }}-strip \
            ./configure \
                --prefix=/usr/local/${{ env.HOST }} \
                --libdir=/usr/local/${{ env.HOST }}/lib \
                --includedir=/usr/local/${{ env.HOST }}/include \
                --static && \
            sudo make install

      - name: Install c-ares
        run: |
            tar xf c-ares-1.17.2.tar.gz && \
            cd c-ares-1.17.2 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --without-random \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
                LIBS="-lws2_32" && \
            sudo make install

      - name: Install libssh2
        run: |
            tar xf libssh2-1.9.0.tar.gz && \
            cd libssh2-1.9.0 && \
            patch -p1 < ../ba149e804ef653cc05ed9803dfc94519ce9328f7.patch && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
                --without-openssl \
                --with-wincng \
                LIBS="-lws2_32" && \
            sudo make install

      - name: Build
        run: |
            curl -L -o version.json https://api.github.com/repos/aria2/aria2/git/refs/heads/master
            git clone https://github.com/aria2/aria2
            cp -rf src/* aria2/src
            cd aria2 && autoreconf -i && ./mingw-config && sudo make
            ${{ env.HOST }}-strip src/aria2c.exe
            
      - name: Archive file
        uses: actions/upload-artifact@v3
        with:
          path: aria2/src/aria2c.exe
