name: Build aria2c.exe

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      
  workflow_dispatch:

env:
  HOST: x86_64-w64-mingw32

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      
      - name: Build
        run: |
            apt-get update && \
            DEBIAN_FRONTEND="noninteractive" \
            apt-get install -y --no-install-recommends \
                make binutils autoconf automake autotools-dev libtool \
                patch ca-certificates \
                pkg-config git curl dpkg-dev gcc-mingw-w64 g++-mingw-w64 \
                autopoint libcppunit-dev libxml2-dev libgcrypt20-dev lzip
            curl -L -O https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz && \
            curl -L -O https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.bz2 && \
            curl -L -O https://www.sqlite.org/2021/sqlite-autoconf-3360000.tar.gz && \
            curl -L -O http://zlib.net/zlib-1.2.11.tar.gz && \
            curl -L -O https://c-ares.haxx.se/download/c-ares-1.17.2.tar.gz && \
            curl -L -O https://www.libssh2.org/download/libssh2-1.9.0.tar.gz && \
            curl -L -O https://github.com/libssh2/libssh2/commit/ba149e804ef653cc05ed9803dfc94519ce9328f7.patch
            tar xf gmp-6.2.1.tar.lz && \
            cd gmp-6.2.1 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --disable-cxx \
                --enable-fat \
                CFLAGS="-mtune=generic -O2 -g0" && \
            make install
            tar xf expat-2.4.1.tar.bz2 && \
            cd ../expat-2.4.1 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
            make install
            RUN tar xf sqlite-autoconf-3360000.tar.gz && \
            cd ../sqlite-autoconf-3360000 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` && \
            make install
            tar xf zlib-1.2.11.tar.gz && \
            cd ../zlib-1.2.11 && \
            CC=${{ env.HOST }}-gcc \
            AR=${{ env.HOST }}-ar \
            LD=${{ env.HOST }}-ld \
            RANLIB=${{ env.HOST }}-ranlib \
            STRIP=${{ env.HOST }}-strip \
            ./configure \
                --prefix=/usr/local/${{ env.HOST }} \
                --libdir=/usr/local/${{ env.HOST }}/lib \
                --includedir=/usr/local/${{ env.HOST }}/include \
                --static && \
            make install
            tar xf c-ares-1.17.2.tar.gz && \
            cd ../c-ares-1.17.2 && \
            ./configure \
                --disable-shared \
                --enable-static \
                --without-random \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
                LIBS="-lws2_32" && \
            make install
            tar xf libssh2-1.9.0.tar.gz && \
            cd ../libssh2-1.9.0 && \
            patch -p1 < ../ba149e804ef653cc05ed9803dfc94519ce9328f7.patch && \
            ./configure \
                --disable-shared \
                --enable-static \
                --prefix=/usr/local/${{ env.HOST }} \
                --host=${{ env.HOST }} \
                --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
                --without-openssl \
                --with-wincng \
                LIBS="-lws2_32" && \
            make install
            cd .. && curl -L -o ./version.json https://api.github.com/repos/aria2/aria2/git/refs/heads/master
            git clone https://github.com/aria2/aria2 && \
                cp -rf src aria2/src  && \
                cd aria2 && autoreconf -i && ./mingw-config && make && \
                ${{ env.HOST }}-strip src/aria2c.exe
            
      - name: Archive pac file
        uses: actions/upload-artifact@v3
        with:
          path: aria2/aria2/src/aria2c.exe
