name: Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch

  workflow_dispatch:

env:
  HOST: x86_64-w64-mingw32

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build
        run: |
            curl -L -o version.json https://api.github.com/repos/aria2/aria2/git/refs/heads/master
            echo $(pwd) >> version.json
            git clone https://github.com/aria2/aria2
            cp -rf src/* aria2/src
            
      - name: Archive file
        uses: actions/upload-artifact@v3
        with:
          path: |
            aria2/src/OptionHandlerFactory.cc
