name: Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch

  workflow_dispatch:

env:
  HOST: x86_64-w64-mingw32

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Archive file
        uses: actions/upload-artifact@v3
        with:
          path: ./*

